// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"github.com/google/uuid"
)

type Urlstore struct {
	Uuid     uuid.UUID
	Longurl  string
	Shorturl string
}
